### ISSUE TITLE
Unable to check if requests are getting a valid response

### ISSUE THREAD

**Issue by SerendipityNL** [needletail/needletail-ui-js#18]
**Is your feature request related to a problem? Please describe.**
As of now there is no way to know if a request send to the API is getting a valid response (status code 2XX), an error (status code 4XX and 5XX) or doesn't go through at all. If you would block the api.needletail.io domain, you wouldn't know what happened.
We have basically the same content rendered with PHP which gets replaced with the response of the server, but when you block the API domain, the content gets replaced with a message saying there is no result, which isn't true, because there are results, just no response.

**Describe the solution you'd like**
An extension to the events that are triggered with the status code received from the server, or a method that gets triggered when no response is retrieved from the server (like the error method on jQuery's ajax method).

**Describe alternatives you've considered**
None so far, because as far as I know there is no way to get to the response object.

**Comment by Edsardio** [comment]
Resolved in v3.0.120
