### ISSUE TITLE
checked option in aggregation hidden by show_more_options

### ISSUE THREAD

**Issue by SerendipityNL** [needletail/needletail-ui-js#21]
**Describe the bug**
An option in the aggregation is selected, but isn't visible on page load, because the show_more_options is used. 

**To Reproduce**
1. Go to https://www.kitcentrum.nl
2. Use the search bar in the header and search for `sikaflex`
3. Scroll down to "Toepassingen" in the aggregation view and click "Toon meer opties"
4. Select the option "Kozijnbewerking"
5. Scroll down to "Toepassingen" again and behold, the option isn't visible.
6. Click "Toon meer opties" and behold, it's visible again

**Expected behavior**
The selected option should stay visible, either by disabling the show_more_options or changing the order in which the options are shown.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 89

**Comment by Edsardio** [comment]
Resolved in v3.0.122
