### ISSUE TITLE
Selecting an option which has results shows empty result message on later pages

### ISSUE THREAD

**Issue by SerendipityNL** [needletail/needletail-ui-js#22]
**Describe the bug**
When you have x results, lets say 30 and you have 12 per page, you will get 3 pages. When you are on page 2 or 3 and select an option in the aggregation bar which would result in less pages, you'll get the message that there are no results

**To Reproduce**
1. Go to https://www.kitcentrum.nl/nl/webshop/zoeken/?search=afdichting&page=2
2. Click on an option in the aggregation bar with less than 12 results
3. See no result message

**Expected behavior**
Switch back to page one. I wouldn't know if this should be the wanted behaviour, even when the page you're on would exist in the new selection, but if it does not, you should see the first page

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version 89

**Comment by Edsardio** [comment]
Resolved in v3.0.122
